We are in the middle of updating the concept of a service to a config based model.
What were previously services are now to be moved to reusable packages, and the packages are configured to run by config files located in the services folder.
This folder contains services that are configured to be ran as such.

When all services are updated, the services folder will be flat.