// SPDX-License-Identifier: GPL-3.0-only
declare module '@promethean/compiler/transform/transformer.js';
declare module '@promethean/dev/harness.js';
declare module '@promethean/fs/fileExplorer.js';
declare module '@promethean/markdown/kanban.js';
declare module '@promethean/markdown/sync.js';
declare module '@promethean/markdown/statuses.js';
declare module '@promethean/markdown/task.js';
declare module '@promethean/parity/normalizers.js';
declare module '@promethean/parity/runner.js';
declare module '@promethean/stream/title.js';
declare module '@promethean/web/url.js';
