// Generated by @promethean-os/shadow-conf
import dotenv from "dotenv";

dotenv.config();

export const apps = 
[
  {
    "name": "lein-repl",
    "script": "lein",
    "interpreter": "/usr/bin/env",
    "args": [
      "repl",
      ":headless",
      ":port",
      "7888"
    ],
    "out_file": "./logs/lein-repl-out.log",
    "error_file": "./logs/lein-repl-err.log",
    "merge_logs": true,
    "instances": 1,
    "autorestart": true,
    "restart_delay": 10000,
    "kill_timeout": 10000,
    "env": {
      "LEIN_REPL_PORT": "7888",
      "JAVA_OPTS": "-Xmx2g -XX:+UseG1GC"
    },
    "ignore_watch": [
      "node_modules",
      "logs",
      "tmp",
      ".git",
      "target",
      ".cpcache"
    ]
  },
  {
    "name": "opencode-indexer",
    "script": "pnpm",
    "args": [
      "opencode-client",
      "indexer",
      "start"
    ],
    "interpreter": "/usr/bin/env",
    "out_file": "./logs/opencode-indexer-out.log",
    "error_file": "./logs/opencode-indexer-err.log",
    "merge_logs": true,
    "instances": 1,
    "autorestart": true,
    "restart_delay": 10000,
    "kill_timeout": 10000,
    "env": {
      "PM2_PROCESS_NAME": "opencode-indexer"
    },
    "cwd": "."
  },
  {
    "name": "opencode-unified-shadow-cljs",
    "script": "pnpm",
    "args": [
      "--filter",
      "@promethean/opencode-unified",
      "dev"
    ],
    "interpreter": "/usr/bin/env",
    "out_file": "./logs/promethean-opencode-unified.log",
    "error_file": "./logs/promthean-opencode-unified.log",
    "merge_logs": true,
    "instances": 1,
    "autorestart": true,
    "restart_delay": 10000,
    "kill_timeout": 10000,
    "env": {
      "PM2_PROCESS_NAME": "opencode-unified-shadow-cljs"
    },
    "cwd": "."
  },
  {
    "name": "opencode-web",
    "script": "bunx",
    "args": [
      "opencode-web",
      "--external-server",
      "http://localhost:4096",
      "--host",
      "0.0.0.0",
      "--port",
      "7799"
    ],
    "interpreter": "/usr/bin/env",
    "out_file": "./logs/opencode-out.log",
    "error_file": "./logs/opencode-err.log",
    "merge_logs": true,
    "instances": 1,
    "autorestart": true,
    "restart_delay": 10000,
    "kill_timeout": 10000,
    "env": {
      "PM2_PROCESS_NAME": "opencode"
    },
    "cwd": "."
  },
  {
    "name": "opencode",
    "script": "opencode",
    "args": [
      "serve",
      "--port",
      4096
    ],
    "interpreter": "/usr/bin/env",
    "out_file": "./logs/opencode-out.log",
    "error_file": "./logs/opencode-err.log",
    "merge_logs": true,
    "instances": 1,
    "autorestart": true,
    "restart_delay": 10000,
    "kill_timeout": 10000,
    "env": {
      "PM2_PROCESS_NAME": "opencode"
    },
    "cwd": "."
  },
  {
    "name": "playwright-mcp",
    "script": "npx",
    "args": [
      "@playwright/mcp@latest",
      "--port",
      "8931"
    ],
    "interpreter": "/usr/bin/env",
    "out_file": "./logs/playwright-mcp-out.log",
    "error_file": "./logs/playwright-mcp-err.log",
    "merge_logs": true,
    "instances": 1,
    "autorestart": true,
    "restart_delay": 10000,
    "kill_timeout": 10000,
    "env": {
      "PM2_PROCESS_NAME": "playwright-mcp"
    },
    "cwd": "."
  },
  {
    "name": "promethean-mcp-dev",
    "script": "pnpm",
    "args": [
      "--filter",
      "@promethean-os/mcp",
      "dev"
    ],
    "interpreter": "/usr/bin/env",
    "out_file": "./logs/promethean-mcp-dev-out.log",
    "error_file": "./logs/promthean-mcp-dev-err.log",
    "merge_logs": true,
    "instances": 1,
    "autorestart": true,
    "restart_delay": 10000,
    "env_file": "./.env",
    "kill_timeout": 10000,
    "env": {
      "PM2_PROCESS_NAME": "promethean-mcp-dev",
      "MCP_USRER_ROLE": "developer",
      "ENABLE_OAUTH": "true"
    },
    "cwd": "."
  },
  {
    "name": "serena",
    "script": "uvx",
    "args": [
      "--from",
      "git+https://github.com/oraios/serena",
      "serena",
      "start-mcp-server",
      "--transport",
      "streamable-http",
      "--port",
      "9121"
    ],
    "interpreter": "/usr/bin/env",
    "out_file": "./logs/serena.log",
    "error_file": "./logs/serena.log",
    "merge_logs": true,
    "instances": 1,
    "autorestart": true,
    "restart_delay": 10000,
    "env_file": "./.env",
    "kill_timeout": 10000,
    "env": {
      "PM2_PROCESS_NAME": "serena"
    },
    "cwd": "."
  },
  {
    "name": "autocommit",
    "script": "pnpm",
    "cwd": ".",
    "args": [
      "autocommit",
      "--path",
      ".",
      "--debounce-ms",
      "10000",
      "--model",
      "error/qwen3:4b-instruct-100k",
      "--base-url",
      "http://localhost:11434"
    ],
    "env": {
      "OPENAI_BASE_URL": "http://localhost:11434",
      "AUTOCOMMIT_MODEL": "error/qwen3:4b-instruct-100k",
      "NODE_ENV": "production"
    },
    "instances": 1,
    "interpreter": "/usr/bin/env",
    "autorestart": true,
    "watch": [
      "./packages/autocommit/dist"
    ],
    "error_file": "/home/err/devel/promethean/logs/autocommit-error.log",
    "out_file": "/home/err/devel/promethean/logs/autocommit-out.log",
    "log_file": "/home/err/devel/promethean/logs/autocommit.log",
    "time": true,
    "kill_timeout": 5000,
    "restart_delay": 5000,
    "max_restarts": 10,
    "min_uptime": 10000
  },
  {
    "name": "broker",
    "script": "index.js",
    "args": [],
    "exec_mode": "fork",
    "out_file": "./logs/broker-out.log",
    "error_file": "./logs/broker-err.log",
    "merge_logs": true,
    "instances": 1,
    "autorestart": true,
    "restart_delay": 10000,
    "kill_timeout": 10000,
    "env": {
      "PM2_PROCESS_NAME": "broker",
      "HEARTBEAT_PORT": "5005",
      "CHECK_INTERVAL": "300000",
      "HEARTBEAT_TIMEOUT": "600000"
    },
    "cwd": "./packages/broker",
    "watch": [
      "./packages/broker"
    ],
    "ignore_watch": [
      "node_modules",
      "logs",
      "tmp",
      ".git"
    ]
  },
  {
    "name": "file-indexer-service",
    "script": "node packages/file-system/file-indexer-service/dist/service.js",
    "cwd": ".",
    "instances": 1,
    "env": {
      "PORT": "3001",
      "NODE_ENV": "production"
    },
    "log_file": "./logs/file-indexer-service.log",
    "out_file": "./logs/file-indexer-service-out.log",
    "error_file": "./logs/file-indexer-service-error.log",
    "log_date_format": "YYYY-MM-DD HH:mm:ss Z",
    "merge_logs": true,
    "max_memory_restart": "1G",
    "watch": [
      "./packages/file-system/file-indexer-service/dist"
    ],
    "ignore_watch": [
      "node_modules",
      "logs"
    ],
    "restart_delay": 4000,
    "max_restarts": 10,
    "min_uptime": "10s"
  },
  {
    "name": "frontend-service",
    "description": "Frontend service with ClojureScript DSL and server capabilities",
    "script": "node",
    "args": [
      "-r",
      "esbuild-register",
      "packages/frontend-service/dist/index.js"
    ],
    "cwd": "..",
    "env": {
      "NODE_ENV": "production",
      "PORT": "3002",
      "LOG_LEVEL": "info"
    },
    "instances": 1,
    "max-memory-restart": "1G",
    "autorestart": true,
    "watch": false,
    "merge-logs": true,
    "log-date-format": "YYYY-MM-DD HH:mm:ss Z",
    "error-file": "logs/frontend-service-error.log",
    "out-file": "logs/frontend-service-out.log",
    "log-file": "logs/frontend-service-combined.log",
    "time": true,
    "kill-timeout": 5000,
    "restart-delay": 4000
  },
  {
    "name": "health",
    "script": "index.js",
    "args": [],
    "exec_mode": "fork",
    "out_file": "./logs/health-out.log",
    "error_file": "./logs/health-err.log",
    "merge_logs": true,
    "instances": 1,
    "autorestart": true,
    "restart_delay": 10000,
    "kill_timeout": 10000,
    "env": {
      "PM2_PROCESS_NAME": "health",
      "HEARTBEAT_PORT": "5005",
      "PYTHONUNBUFFERED": "1",
      "PYTHONPATH": "./packages/pm2-helpers",
      "CHECK_INTERVAL": "300000",
      "HEARTBEAT_TIMEOUT": "600000"
    },
    "cwd": "./packages/health",
    "watch": [
      "./packages/health"
    ],
    "ignore_watch": [
      "node_modules",
      "logs",
      "tmp",
      ".git"
    ]
  },
  {
    "name": "heartbeat",
    "script": "index.js",
    "args": [],
    "exec_mode": "fork",
    "out_file": "./logs/heartbeat-out.log",
    "error_file": "./logs/heartbeat-err.log",
    "merge_logs": true,
    "instances": 1,
    "autorestart": true,
    "restart_delay": 10000,
    "kill_timeout": 10000,
    "env": {
      "PM2_PROCESS_NAME": "heartbeat",
      "HEARTBEAT_PORT": "5005",
      "PYTHONUNBUFFERED": "1",
      "CHECK_INTERVAL": "300000",
      "HEARTBEAT_TIMEOUT": "600000"
    },
    "cwd": "./packages/heartbeat",
    "watch": [
      "./packages/heartbeat"
    ],
    "ignore_watch": [
      "node_modules",
      "logs",
      "tmp",
      ".git"
    ]
  },
  {
    "name": "openai-server",
    "description": "OpenAI-compatible API server with Ollama integration and task queuing",
    "script": "node",
    "args": [
      "-r",
      "esbuild-register",
      "packages/openai-server/dist/index.js"
    ],
    "cwd": "..",
    "env": {
      "NODE_ENV": "production",
      "PORT": "3001",
      "LOG_LEVEL": "info"
    },
    "instances": 1,
    "max-memory-restart": "1G",
    "autorestart": true,
    "watch": false,
    "merge-logs": true,
    "log-date-format": "YYYY-MM-DD HH:mm:ss Z",
    "error-file": "logs/openai-server-error.log",
    "out-file": "logs/openai-server-out.log",
    "log-file": "logs/openai-server-combined.log",
    "time": true,
    "kill-timeout": 5000,
    "restart-delay": 4000
  }
];

export const triggers = 
[];

export const schedules = 
[];

export const actions = 
[];
