// Generated by @promethean/shadow-conf
import dotenv from "dotenv";

try {
  dotenv.config();
} catch (error) {
  if (error?.code !== "ERR_MODULE_NOT_FOUND") {
    throw error;
  }
}

export const apps = 
[
  {
    "name": "lein-repl",
    "script": "lein",
    "interpreter": "/usr/bin/env",
    "args": [
      "repl",
      ":headless",
      ":port",
      "7888"
    ],
    "out_file": "./logs/lein-repl-out.log",
    "error_file": "./logs/lein-repl-err.log",
    "merge_logs": true,
    "instances": 1,
    "autorestart": true,
    "restart_delay": 10000,
    "kill_timeout": 10000,
    "env": {
      "LEIN_REPL_PORT": "7888",
      "JAVA_OPTS": "-Xmx2g -XX:+UseG1GC"
    },
    "ignore_watch": [
      "node_modules",
      "logs",
      "tmp",
      ".git",
      "target",
      ".cpcache"
    ]
  },
  {
    "name": "opencode",
    "script": "opencode",
    "args": [
      "serve",
      "--port",
      4096
    ],
    "interpreter": "/usr/bin/env",
    "out_file": "./logs/opencode-out.log",
    "error_file": "./logs/opencode-err.log",
    "merge_logs": true,
    "instances": 1,
    "autorestart": true,
    "restart_delay": 10000,
    "kill_timeout": 10000,
    "env": {
      "PM2_PROCESS_NAME": "opencode"
    },
    "cwd": "."
  },
  {
    "name": "broker",
    "script": "index.js",
    "args": [],
    "exec_mode": "fork",
    "out_file": "./logs/broker-out.log",
    "error_file": "./logs/broker-err.log",
    "merge_logs": true,
    "instances": 1,
    "autorestart": true,
    "restart_delay": 10000,
    "kill_timeout": 10000,
    "env": {
      "PM2_PROCESS_NAME": "broker",
      "HEARTBEAT_PORT": "5005",
      "CHECK_INTERVAL": "300000",
      "HEARTBEAT_TIMEOUT": "600000"
    },
    "cwd": "./packages/broker",
    "watch": [
      "./packages/broker"
    ],
    "ignore_watch": [
      "node_modules",
      "logs",
      "tmp",
      ".git"
    ]
  },
  {
    "name": "dualstore-http",
    "description": "Dual-store HTTP API server for events and agent tasks",
    "script": "node",
    "args": [
      "packages/dualstore-http/dist/index-simple.js"
    ],
    "cwd": "..",
    "env": {
      "NODE_ENV": "production",
      "PORT": "3000",
      "LOG_LEVEL": "info",
      "DUALSTORE_HTTP_HOST": "localhost",
      "DUALSTORE_HTTP_PORT": "3000"
    },
    "instances": 1,
    "max-memory-restart": "512M",
    "autorestart": true,
    "watch": [
      "packages/dualstore-http/dist"
    ],
    "merge-logs": true,
    "log-date-format": "YYYY-MM-DD HH:mm:ss Z",
    "error-file": "logs/dualstore-http-error.log",
    "out-file": "logs/dualstore-http-out.log",
    "log-file": "logs/dualstore-http-combined.log",
    "time": true,
    "kill-timeout": 5000,
    "restart-delay": 4000
  },
  {
    "name": "frontend-service",
    "description": "Frontend service with ClojureScript DSL and server capabilities",
    "script": "node",
    "args": [
      "-r",
      "esbuild-register",
      "packages/frontend-service/dist/index.js"
    ],
    "cwd": "..",
    "env": {
      "NODE_ENV": "production",
      "PORT": "3002",
      "LOG_LEVEL": "info"
    },
    "instances": 1,
    "max-memory-restart": "1G",
    "autorestart": true,
    "watch": false,
    "merge-logs": true,
    "log-date-format": "YYYY-MM-DD HH:mm:ss Z",
    "error-file": "logs/frontend-service-error.log",
    "out-file": "logs/frontend-service-out.log",
    "log-file": "logs/frontend-service-combined.log",
    "time": true,
    "kill-timeout": 5000,
    "restart-delay": 4000
  },
  {
    "name": "health",
    "script": "index.js",
    "args": [],
    "exec_mode": "fork",
    "out_file": "./logs/health-out.log",
    "error_file": "./logs/health-err.log",
    "merge_logs": true,
    "instances": 1,
    "autorestart": true,
    "restart_delay": 10000,
    "kill_timeout": 10000,
    "env": {
      "PM2_PROCESS_NAME": "health",
      "HEARTBEAT_PORT": "5005",
      "PYTHONUNBUFFERED": "1",
      "PYTHONPATH": "./packages/pm2-helpers",
      "CHECK_INTERVAL": "300000",
      "HEARTBEAT_TIMEOUT": "600000"
    },
    "cwd": "./packages/health",
    "watch": [
      "./packages/health"
    ],
    "ignore_watch": [
      "node_modules",
      "logs",
      "tmp",
      ".git"
    ]
  },
  {
    "name": "heartbeat",
    "script": "index.js",
    "args": [],
    "exec_mode": "fork",
    "out_file": "./logs/heartbeat-out.log",
    "error_file": "./logs/heartbeat-err.log",
    "merge_logs": true,
    "instances": 1,
    "autorestart": true,
    "restart_delay": 10000,
    "kill_timeout": 10000,
    "env": {
      "PM2_PROCESS_NAME": "heartbeat",
      "HEARTBEAT_PORT": "5005",
      "PYTHONUNBUFFERED": "1",
      "PYTHONPATH": "./packages/pm2-helpers",
      "CHECK_INTERVAL": "300000",
      "HEARTBEAT_TIMEOUT": "600000"
    },
    "cwd": "./packages/heartbeat",
    "watch": [
      "./packages/heartbeat"
    ],
    "ignore_watch": [
      "node_modules",
      "logs",
      "tmp",
      ".git"
    ]
  },
  {
    "name": "openai-server",
    "description": "OpenAI-compatible API server with Ollama integration and task queuing",
    "script": "node",
    "args": [
      "-r",
      "esbuild-register",
      "packages/openai-server/dist/index.js"
    ],
    "cwd": "..",
    "env": {
      "NODE_ENV": "production",
      "PORT": "3001",
      "LOG_LEVEL": "info"
    },
    "instances": 1,
    "max-memory-restart": "1G",
    "autorestart": true,
    "watch": false,
    "merge-logs": true,
    "log-date-format": "YYYY-MM-DD HH:mm:ss Z",
    "error-file": "logs/openai-server-error.log",
    "out-file": "logs/openai-server-out.log",
    "log-file": "logs/openai-server-combined.log",
    "time": true,
    "kill-timeout": 5000,
    "restart-delay": 4000
  }
];

export const triggers = 
[];

export const schedules = 
[];

export const actions = 
[];
