pipelines:
  - name: docs
    steps:
      - id: symdocs-scan
        cwd: .
        shell: "pnpm --filter @promethean/symdocs symdocs:01-scan --root packages --tsconfig ./config/tsconfig.base.json"
        inputs: ["packages/**/{src,lib}/**/*.{ts,tsx,js,jsx}"]
        outputs: [".cache/symdocs/symbols.json"]
      - id: symdocs-docs
        deps: ["symdocs-scan"]
        shell: "pnpm --filter @promethean/symdocs symdocs:02-docs --model qwen3:4b"
        inputs: [".cache/symdocs/symbols.json"]
        outputs: [".cache/symdocs/docs.json"]
      - id: symdocs-write
        deps: ["symdocs-docs"]
        shell: "pnpm --filter @promethean/symdocs symdocs:03-write --out docs/packages --granularity module"
        inputs: [".cache/symdocs/docs.json"]
        outputs: ["docs/packages/**/**/*.md"]
      - id: symdocs-graph
        deps: ["symdocs-scan"]
        shell: "pnpm --filter @promethean/symdocs symdocs:04-graph"
        inputs:
          [
            "packages/**/package.json",
            "packages/**/{src,lib}/**/*.{ts,tsx,js,jsx}",
          ]
        outputs: ["docs/packages/README.md", "docs/packages/**/README.md"]

  - name: simtasks
    steps:
      - id: simtasks-scan
        shell: "pnpm --filter @promethean/simtasks sim:01-scan --root packages --tsconfig ./tsconfig.json"
        inputs: ["packages/**/{src,lib}/**/*.{ts,tsx,js,jsx}"]
        outputs: [".cache/simtasks/functions.json"]
      - id: simtasks-embed
        deps: ["simtasks-scan"]
        shell: "pnpm --filter @promethean/simtasks sim:02-embed --embed-model nomic-embed-text:latest"
        inputs: [".cache/simtasks/functions.json"]
        outputs: [".cache/simtasks/embeddings.json"]
      - id: simtasks-cluster
        deps: ["simtasks-embed"]
        shell: "pnpm --filter @promethean/simtasks sim:03-cluster --sim-threshold 0.86 --k 12 --min-size 2"
        inputs: [".cache/simtasks/embeddings.json"]
        outputs: [".cache/simtasks/clusters.json"]
      - id: simtasks-plan
        deps: ["simtasks-cluster"]
        shell: "pnpm --filter @promethean/simtasks sim:04-plan --model qwen3:4b --base-dir packages"
        inputs: [".cache/simtasks/clusters.json"]
        outputs: [".cache/simtasks/plans.json"]
      - id: simtasks-write
        deps: ["simtasks-plan"]
        shell: "pnpm --filter @promethean/simtasks sim:05-write --out docs/agile/tasks"
        inputs: [".cache/simtasks/plans.json"]
        outputs: ["docs/agile/tasks/*.md"]

  - name: codemods
    steps:
      - id: mods-spec
        shell: "pnpm --filter @promethean/codemods mods:01-spec --tsconfig ./tsconfig.json"
        inputs: [".cache/simtasks/{functions,clusters,plans}.json"]
        outputs: [".cache/codemods/specs.json"]
      - id: mods-generate
        deps: ["mods-spec"]
        shell: "pnpm --filter @promethean/codemods mods:02-generate"
        inputs: [".cache/codemods/specs.json"]
        outputs: ["codemods/**/transform.ts"]
      - id: mods-dry-run
        deps: ["mods-generate"]
        shell: "pnpm --filter @promethean/codemods mods:03-dry-run --root packages --report docs/agile/tasks/codemods --specs .cache/codemods/specs.json --delete-duplicates true"
        inputs:
          [
            "codemods/**/transform.ts",
            "packages/**/{src,lib}/**/*.{ts,tsx,js,jsx}",
          ]
        outputs: ["docs/agile/tasks/codemods/*.md"]
      - id: mods-apply
        deps: ["mods-dry-run"]
        shell: "pnpm --filter @promethean/codemods mods:03-apply --root packages --report docs/agile/tasks/codemods --specs .cache/codemods/specs.json --delete-duplicates true"
        inputs: ["codemods/**/transform.ts"]
        outputs: [".cache/codemods/run-apply.json"]
      - id: mods-verify
        deps: ["mods-apply"]
        shell: 'pnpm --filter @promethean/codemods mods:04-verify:after --stage after --test "pnpm -w -r test"'
        inputs: [".cache/codemods/run-apply.json"]
        outputs:
          [
            "docs/agile/tasks/codemods/verify-after.md",
            "docs/agile/tasks/codemods/VERIFY.md",
          ]
  - name: semver-guard
    steps:
      - id: sv-snapshot
        shell: "pnpm --filter @promethean/semverguard sv:01-snapshot --root packages --tsconfig ./tsconfig.json --out .cache/semverguard/snapshot.json"
        inputs:
          - "packages/**/package.json"
          - "packages/**/{src,lib}/**/*.{ts,tsx,js,jsx}"
        outputs: [".cache/semverguard/snapshot.json"]

      - id: sv-diff
        deps: ["sv-snapshot"]
        shell: "pnpm --filter @promethean/semverguard sv:02-diff --current .cache/semverguard/snapshot.json --baseline git:origin/main:.cache/semverguard/snapshot.json --out .cache/semverguard/diff.json"
        inputs: [".cache/semverguard/snapshot.json"]
        outputs: [".cache/semverguard/diff.json"]

      - id: sv-plan
        deps: ["sv-diff"]
        shell: "pnpm --filter @promethean/semverguard sv:03-plan --diff .cache/semverguard/diff.json --out .cache/semverguard/plans.json --model qwen3:4b"
        inputs: [".cache/semverguard/diff.json"]
        outputs: [".cache/semverguard/plans.json"]

      - id: sv-write
        deps: ["sv-plan"]
        shell: "pnpm --filter @promethean/semverguard sv:04-write --plans .cache/semverguard/plans.json --out docs/agile/tasks/semver"
        inputs: [".cache/semverguard/plans.json"]
        outputs: ["docs/agile/tasks/semver/*.md"]

      - id: sv-pr
        deps: ["sv-write"]
        shell: "pnpm --filter @promethean/semverguard sv:05-pr --plans .cache/semverguard/plans.json --root packages --mode prepare --update-dependents true --dep-range preserve"
        inputs:
          - ".cache/semverguard/plans.json"
          - "packages/**/package.json"
        outputs:
          - ".cache/semverguard/pr/summary.json"
  - name: board-review
    steps:
      - id: br-fm
        shell: "pnpm --filter @promethean/boardrev br:01-fm"
        inputs: ["docs/agile/tasks/**/*.md"]
        outputs: ["docs/agile/tasks/**/*.md"] # FM updates in-place
      - id: br-prompts
        deps: ["br-fm"]
        shell: "pnpm --filter @promethean/boardrev br:02-prompts --process docs/agile/Process.md --out .cache/boardrev/prompts.json"
        inputs: ["docs/agile/Process.md"]
        outputs: [".cache/boardrev/prompts.json"]
      - id: br-index
        deps: ["br-fm"]
        shell: 'pnpm --filter @promethean/boardrev br:03-index --globs "{README.md,docs/**/*.md,packages/**/{src,lib}/**/*.{ts,tsx,js,jsx}}"'
        inputs:
          - "README.md"
          - "docs/**/*.md"
          - "packages/**/{src,lib}/**/*.{ts,tsx,js,jsx}"
        outputs:
          - ".cache/boardrev/repo-index.json"
          - ".cache/boardrev/repo-embeddings.json"
      - id: br-match
        deps: ["br-prompts", "br-index"]
        shell: "pnpm --filter @promethean/boardrev br:04-match --tasks docs/agile/tasks --k 8"
        inputs:
          - "docs/agile/tasks/**/*.md"
          - ".cache/boardrev/repo-index.json"
          - ".cache/boardrev/repo-embeddings.json"
        outputs: [".cache/boardrev/context.json"]
      - id: br-eval
        deps: ["br-match"]
        shell: "pnpm --filter @promethean/boardrev br:05-eval --model qwen3:4b"
        inputs:
          - ".cache/boardrev/prompts.json"
          - ".cache/boardrev/context.json"
        outputs: [".cache/boardrev/evals.json"]
      - id: br-report
        deps: ["br-eval"]
        shell: "pnpm --filter @promethean/boardrev br:06-report --outDir docs/agile/reports"
        inputs: [".cache/boardrev/evals.json"]
        outputs: ["docs/agile/reports/*.md"]
  - name: sonar
    steps:
      - id: sonar-scan
        cwd: .
        shell: "sonar-scanner" # expects sonar-project.properties in repo OR env overrides
        env:
          SONAR_HOST_URL: "${SONAR_HOST_URL}"
          SONAR_TOKEN: "${SONAR_TOKEN}"
          SONAR_PROJECT_KEY: "${SONAR_PROJECT_KEY}"
        inputs:
          - "packages/**/{src,lib}/**/*.{ts,tsx,js,jsx}"
          - "sonar-project.properties"
        outputs:
          - ".cache/sonar/scan.touch" # marker file we create after scan
      - id: sonar-fetch
        deps: ["sonar-scan"]
        shell: "pnpm --filter @promethean/sonarflow sonar:fetch --project ${SONAR_PROJECT_KEY} --out .cache/sonar/issues.json"
        inputs: []
        outputs: [".cache/sonar/issues.json"]
      - id: sonar-plan
        deps: ["sonar-fetch"]
        shell: "pnpm --filter @promethean/sonarflow sonar:plan --in .cache/sonar/issues.json --out .cache/sonar/plans.json --group-by rule+prefix --prefix-depth 2 --min-group 2 --model qwen3:4b"
        inputs: [".cache/sonar/issues.json"]
        outputs: [".cache/sonar/plans.json"]
      - id: sonar-write
        deps: ["sonar-plan"]
        shell: "pnpm --filter @promethean/sonarflow sonar:write --in .cache/sonar/plans.json --out docs/agile/tasks/sonar"
        inputs: [".cache/sonar/plans.json"]
        outputs: ["docs/agile/tasks/sonar/*.md"]
  - name: readmes
    steps:
      - id: rm-scan
        shell: "pnpm --filter @promethean/readmeflow rm:01-scan --root packages --out .cache/readmes/scan.json"
        inputs:
          - "packages/**/package.json"
          - "packages/**/tsconfig.json"
        outputs:
          - ".cache/readmes/scan.json"

      - id: rm-outline
        deps: ["rm-scan"]
        shell: "pnpm --filter @promethean/readmeflow rm:02-outline --scan .cache/readmes/scan.json --out .cache/readmes/outlines.json --model qwen3:4b"
        env:
          OLLAMA_URL: "${OLLAMA_URL}"
        inputs:
          - ".cache/readmes/scan.json"
        outputs:
          - ".cache/readmes/outlines.json"

      - id: rm-write
        deps: ["rm-outline"]
        shell: "pnpm --filter @promethean/readmeflow rm:03-write --scan .cache/readmes/scan.json --outlines .cache/readmes/outlines.json --mermaid true"
        inputs:
          - ".cache/readmes/outlines.json"
        outputs:
          - "packages/**/README.md"

      - id: rm-verify
        deps: ["rm-write"]
        shell: "pnpm --filter @promethean/readmeflow rm:04-verify --root packages --out docs/agile/reports/readmes"
        inputs:
          - "packages/**/README.md"
        outputs:
          - "docs/agile/reports/readmes/*.md"
  - name: buildfix
    steps:
      - id: bf-errors
        shell: "pnpm --filter @promethean/buildfix bf:01-errors --tsconfig tsconfig.json --out .cache/buildfix/errors.json"
        inputs:
          - "tsconfig.json"
          - "packages/**/{src,lib}/**/*.{ts,tsx,js,jsx}"
        outputs:
          - ".cache/buildfix/errors.json"

      - id: bf-iterate
        deps: ["bf-errors"]
        shell: >
          pnpm --filter @promethean/buildfix
          bf:02-iterate
          --errors .cache/buildfix/errors.json
          --out .cache/buildfix
          --model qwen3:4b
          --max-cycles 5
          --git per-error
          --commit-on always
          --branch-prefix buildfix
          --remote origin
          --push false
          --use-gh false
          --rollback-on-regress true
        env:
          OLLAMA_URL: "${OLLAMA_URL}"
        inputs:
          - ".cache/buildfix/errors.json"
          - "tsconfig.json"
          - "packages/**/{src,lib}/**/*.{ts,tsx,js,jsx}"
        outputs:
          - ".cache/buildfix/summary.json"
          - ".cache/buildfix/history/**"
          - ".cache/buildfix/snippets/**"

      - id: bf-report
        deps: ["bf-iterate"]
        shell: "pnpm --filter @promethean/buildfix bf:03-report --summary .cache/buildfix/summary.json --history-root .cache/buildfix/history --out docs/agile/reports/buildfix"
        inputs:
          - ".cache/buildfix/summary.json"
        outputs:
          - "docs/agile/reports/buildfix/*.md"
  - name: test-gap
    steps:
      # (Optional) upstream: run your tests to produce lcov.info
      # - id: tg-run-tests
      #   shell: "pnpm -w test -- --coverage"   # or your workspace runner
      #   outputs: ["coverage/lcov.info", "packages/**/coverage/lcov.info"]

      - id: tg-exports
        shell: "pnpm --filter @promethean/testgap tg:01-scan-exports --root packages --out .cache/testgap/exports.json"
        inputs:
          - "packages/**/package.json"
          - "packages/**/{src,lib}/**/*.{ts,tsx,js,jsx}"
        outputs:
          - ".cache/testgap/exports.json"

      - id: tg-coverage
        # deps: ["tg-run-tests"]
        shell: 'pnpm --filter @promethean/testgap tg:02-read-coverage --lcov-globs "{coverage/lcov.info,packages/**/coverage/lcov.info}" --out .cache/testgap/coverage.json'
        inputs:
          - "coverage/lcov.info"
          - "packages/**/coverage/lcov.info"
        outputs:
          - ".cache/testgap/coverage.json"

      - id: tg-map
        deps: ["tg-exports", "tg-coverage"]
        shell: "pnpm --filter @promethean/testgap tg:03-map-gaps --exports .cache/testgap/exports.json --coverage .cache/testgap/coverage.json --min-lines 3 --out .cache/testgap/gaps.json"
        inputs:
          - ".cache/testgap/exports.json"
          - ".cache/testgap/coverage.json"
        outputs:
          - ".cache/testgap/gaps.json"
      - id: tg-gate
        deps: ["tg-map"]
        shell: "pnpm --filter @promethean/testgap tg:08-gate --gaps .cache/testgap/gaps.json --out .cache/testgap/gate.json --threshold 0.70 --metric symbols"
        inputs: [".cache/testgap/gaps.json"]
        outputs: [".cache/testgap/gate.json"]

      - id: tg-cookbook
        deps: ["tg-map"]
        shell: "pnpm --filter @promethean/testgap tg:04-cookbook-cross --recipes docs/cookbook/**/*.md --out .cache/testgap/cookbook.json"
        inputs:
          - "docs/cookbook/**/*.md"
        outputs:
          - ".cache/testgap/cookbook.json"

      - id: tg-plan
        deps: ["tg-cookbook"]
        shell: "pnpm --filter @promethean/testgap tg:05-plan --gaps .cache/testgap/gaps.json --cookbook .cache/testgap/cookbook.json --out .cache/testgap/plans.json --model qwen3:4b --threshold 0.5 --max-per-pkg 15"
        env:
          OLLAMA_URL: "${OLLAMA_URL}"
        inputs:
          - ".cache/testgap/gaps.json"
          - ".cache/testgap/cookbook.json"
        outputs:
          - ".cache/testgap/plans.json"

      - id: tg-write
        deps: ["tg-plan"]
        shell: "pnpm --filter @promethean/testgap tg:06-write --plans .cache/testgap/plans.json --out docs/agile/tasks/test-gaps"
        inputs:
          - ".cache/testgap/plans.json"
        outputs:
          - "docs/agile/tasks/test-gaps/*.md"

      - id: tg-report
        deps: ["tg-map"]
        shell: "pnpm --filter @promethean/testgap tg:07-report --gaps .cache/testgap/gaps.json --out docs/agile/reports/test-gaps"
        inputs:
          - ".cache/testgap/gaps.json"
        outputs:
          - "docs/agile/reports/test-gaps/*.md"
  - name: docops
    steps:
      # a) Ensure / complete front matter (filename/description/tags/uuid)
      - id: doc-fm
        shell: >
          pnpm --filter @promethean/docops
          doc:01-fm-ensure
          --dir docs/unique
          --gen-model qwen3:4b
        env:
          OLLAMA_URL: "${OLLAMA_URL}"
        inputs:
          - "docs/unique/**/*.md"
        outputs:
          - ".cache/docops/frontmatters.json"

      # b) Chunk + embed (language-aware tokenizer) and build index
      - id: doc-index
        deps: ["doc-fm"]
        shell: >
          pnpm --filter @promethean/docops
          doc:02-chunk-embed
          --dir docs/unique
          --embed-model nomic-embed-text:latest
        env:
          OLLAMA_URL: "${OLLAMA_URL}"
        inputs:
          - "docs/unique/**/*.md"
          - ".cache/docops/frontmatters.json"
        outputs:
          - ".cache/docops/chunks.json"
          - ".cache/docops/embeddings.json"

      # c) Cross-document similarity queries (cache per-chunk results)
      - id: doc-similarity
        deps: ["doc-index"]
        shell: >
          pnpm --filter @promethean/docops
          doc:03-similarity
          --chunks .cache/docops/chunks.json
          --embeddings .cache/docops/embeddings.json
          --out .cache/docops/queries.json
        inputs:
          - ".cache/docops/chunks.json"
          - ".cache/docops/embeddings.json"
        outputs:
          - ".cache/docops/queries.json"

      # d) Compute related-doc scores (doc↔doc)
      - id: doc-related
        deps: ["doc-similarity"]
        shell: >
          pnpm --filter @promethean/docops
          doc:04-related
          --queries .cache/docops/queries.json
          --frontmatter .cache/docops/frontmatters.json
          --threshold 0.62
          --out .cache/docops/related.json
        inputs:
          - ".cache/docops/queries.json"
          - ".cache/docops/frontmatters.json"
        outputs:
          - ".cache/docops/related.json"

      # e) High-scoring references (chunk-level, with line/col)
      - id: doc-references
        deps: ["doc-similarity"]
        shell: >
          pnpm --filter @promethean/docops
          doc:05-references
          --queries .cache/docops/queries.json
          --chunks .cache/docops/chunks.json
          --ref-threshold 0.75
          --out .cache/docops/references.json
        inputs:
          - ".cache/docops/queries.json"
          - ".cache/docops/chunks.json"
        outputs:
          - ".cache/docops/references.json"

      # f) Apply FM updates (add related & references into FM only)
      - id: doc-apply-fm
        deps: ["doc-related", "doc-references"]
        shell: >
          pnpm --filter @promethean/docops
          doc:06-apply-frontmatter
          --root docs/unique
          --frontmatter .cache/docops/frontmatters.json
          --related .cache/docops/related.json
          --references .cache/docops/references.json
        inputs:
          - ".cache/docops/frontmatters.json"
          - ".cache/docops/related.json"
          - ".cache/docops/references.json"
        outputs:
          - ".cache/docops/applied-fm.touch"

      # g) Footer writer (markdown links with line anchors)
      - id: doc-footer
        deps: ["doc-apply-fm"]
        shell: >
          pnpm --filter @promethean/docops
          doc:07-write-footer
          --root docs/unique
          --references .cache/docops/references.json
          --related .cache/docops/related.json
          --style obsidian
        inputs:
          - ".cache/docops/references.json"
          - ".cache/docops/related.json"
          - "docs/unique/**/*.md"
        outputs:
          - ".cache/docops/footer.touch"

      # h) Optional rename pass (based on generated titles)
      - id: doc-rename
        deps: ["doc-apply-fm"]
        shell: >
          pnpm --filter @promethean/docops
          doc:08-rename
          --root docs/unique
          --frontmatter .cache/docops/frontmatters.json
          --out .cache/docops/renames.json
        inputs:
          - ".cache/docops/frontmatters.json"
        outputs:
          - ".cache/docops/renames.json"
