packages:
  - packages/*
  - packages/*/*
  - .opencode/*
  - scripts/*/*
  - tools/

auditConfig:
  ignoreCves:
    - packages/buildfix/benchmark-fixtures
    - packages/buildfix/simple-benchmark-temp
    - packages/buildfix/large-benchmark-temp
    - packages/buildfix/test-fixtures
    - packages/buildfix/simple-fixtures
    - packages/buildfix/test-tmp
    - pseudo/*

ignore:
  - packages/buildfix/benchmark-fixtures
  - packages/buildfix/simple-benchmark-temp
  - packages/buildfix/large-benchmark-temp
  - packages/buildfix/test-fixtures
  - packages/buildfix/simple-fixtures
  - packages/buildfix/test-tmp
  - pseudo/*

link-workspace-packages: true

pnpm:
  overrides:
    tinyglobby:
      '@types/node': 20.19.11

prefer-workspace-packages: true
