(ns clj-hacks.mcp.adapter-elisp-test
  (:require [babashka.fs :as fs]
            [clj-hacks.mcp.adapter-elisp :as adapter]
            [clojure.string :as str]
            [clojure.test :refer :all]))

(def sample-elisp
  (str "(with-eval-after-load 'mcp\n"
       "  (message \"noop\"))\n\n"
       "(message \"before-block\")\n\n"
       ";; AUTO-GENERATED by mk.mcp-cli -- edits will be overwritten.\n"
       "(with-eval-after-load 'mcp\n"
       "  (setq mcp-hub-servers\n"
       "        '(( \"github\" .\n"
       "            (:command \"/home/err/devel/promethean/scripts/mcp/bin/github.sh\"))\n"
       "          ( \"npm-helper\" .\n"
       "            (:command \"npx\"\n"
       "                      :args (\"-y\" \"@pinkpixel/npm-helper-mcp\")\n"
       "                      :cwd \"$HOME/devel/promethean\"))\n"
       "          )))\n"
       "(message \"after-block\")\n"))

(deftest read-full-parses-hub-servers
  (let [tmp  (fs/create-temp-file {:prefix "mcp-elisp-" :suffix ".el"})
        path (str tmp)]
    (spit path sample-elisp)
    (let [{:keys [mcp rest raw]} (adapter/read-full path)
          servers (:mcp-servers mcp)]
      (is (= "/home/err/devel/promethean/scripts/mcp/bin/github.sh"
             (get-in servers [:github :command])))
      (is (= ["-y" "@pinkpixel/npm-helper-mcp"]
             (get-in servers [:npm-helper :args])))
      (is (= "$HOME/devel/promethean"
             (get-in servers [:npm-helper :cwd])))
      (is (map? rest))
      (is (str/includes? (:before rest) "(message \"before-block\")"))
      (is (str/includes? (:after rest) "(message \"after-block\")"))
      (is (string? raw)))))

(deftest write-full-renders-new-format
  (let [tmp     (fs/create-temp-file {:prefix "mcp-elisp-out-" :suffix ".el"})
        path    (str tmp)
        servers {:github {:command "/home/err/devel/promethean/scripts/mcp/bin/github.sh"}
                 :npm-helper {:command "npx"
                              :args ["-y" "@pinkpixel/npm-helper-mcp"]
                              :cwd "$HOME/devel/promethean"}}
        data    {:mcp {:mcp-servers servers}
                 :rest {:before ";; header\n"
                        :after "(message \"tail\")\n"}}]
    (adapter/write-full path data)
    (let [out (slurp path)]
      (is (str/starts-with? out ";; header\n;; AUTO-GENERATED"))
      (is (str/includes? out "(:command \"npx\""))
      (is (str/includes? out "(message \"tail\")\n")))))