version: "3.9"

networks:
  prom-net:
    driver: bridge

# central volumes (adjust paths as you like)
volumes:
  grafana_data:
  prometheus_data:
  loki_data:
  tempo_data:
  postgres_data:
  mongo_data:
  redis_data:
  meili_data:
  minio_data:
  portainer_data:
  gitea_data:
  drone_data:
  woodpecker_data:
  sonarqube_data:
  nats_data:
  rabbitmq_data:
  mosquitto_data:
  temporal_data:
  airflow_db_data:
  airflow_dags_data:
  code_server_data:
  opensearch_data:

# ---------- EDGE (choose one) ----------
services:
  traefik:
    profiles: ["edge"]
    image: traefik:v3.1
    command:
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      # uncomment if using tls
      # - "--entrypoints.websecure.address=:443"
      # - "--certificatesresolvers.le.acme.tlschallenge=true"
      # - "--certificatesresolvers.le.acme.email=${ACME_EMAIL}"
      # - "--certificatesresolvers.le.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      # - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # - ./infra/traefik/letsencrypt:/letsencrypt
    networks: [prom-net]
    restart: unless-stopped

  edge-nginx:
    profiles: ["edge"]
    image: nginx:1.27-alpine
    ports: ["80:80"]
    volumes:
      - ./infra/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./infra/nginx/secrets:/etc/nginx/secrets:ro
    networks: [prom-net]
    restart: unless-stopped

  # ---------- OBSERVABILITY ----------
  prometheus:
    profiles: ["observability"]
    image: prom/prometheus:v3.0.0
    volumes:
      - prometheus_data:/prometheus
      - ./infra/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    networks: [prom-net]
    restart: unless-stopped

  grafana:
    profiles: ["observability"]
    image: grafana/grafana:11.2.0
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASS:-admin}
    volumes:
      - grafana_data:/var/lib/grafana
      - ./infra/grafana/provisioning:/etc/grafana/provisioning
    ports:
      - "3000:3000"
    networks: [prom-net]
    restart: unless-stopped

  loki:
    profiles: ["observability"]
    image: grafana/loki:3.1.1
    command: ["-config.file=/etc/loki/loki-config.yaml"]
    volumes:
      - loki_data:/loki
      - ./infra/loki/loki-config.yaml:/etc/loki/loki-config.yaml:ro
    networks: [prom-net]
    restart: unless-stopped

  promtail:
    profiles: ["observability"]
    image: grafana/promtail:3.1.1
    command: ["-config.file=/etc/promtail/config.yaml"]
    volumes:
      - /var/log:/var/log:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - ./infra/promtail/config.yaml:/etc/promtail/config.yaml:ro
    networks: [prom-net]
    restart: unless-stopped

  tempo:
    profiles: ["observability"]
    image: grafana/tempo:2.6.0
    command: ["-config.file=/etc/tempo/tempo.yaml"]
    volumes:
      - tempo_data:/var/tempo
      - ./infra/tempo/tempo.yaml:/etc/tempo/tempo.yaml:ro
    networks: [prom-net]
    restart: unless-stopped

  cadvisor:
    profiles: ["observability"]
    image: gcr.io/cadvisor/cadvisor:v0.49.2
    privileged: true
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - "8080:8080"
    networks: [prom-net]
    restart: unless-stopped

  node_exporter:
    profiles: ["observability"]
    image: prom/node-exporter:v1.8.2
    pid: host
    network_mode: host
    restart: unless-stopped

  portainer:
    profiles: ["observability"]
    image: portainer/portainer-ce:2.21.5
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    ports:
      - "9443:9443"
    networks: [prom-net]
    restart: unless-stopped

  # ---------- DATA LAYER ----------
  postgres:
    profiles: ["data"]
    image: postgres:16-alpine
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-app}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports: ["5432:5432"]
    networks: [prom-net]
    restart: unless-stopped

  mongo:
    profiles: ["data"]
    image: mongo:7
    volumes:
      - mongo_data:/data/db
    ports: ["27017:27017"]
    networks: [prom-net]
    restart: unless-stopped

  redis:
    profiles: ["data"]
    image: redis:7-alpine
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data
    ports: ["6379:6379"]
    networks: [prom-net]
    restart: unless-stopped

  meilisearch:
    profiles: ["data", "search"]
    image: getmeili/meilisearch:v1.12
    environment:
      - MEILI_NO_ANALYTICS=true
      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY:-meili}
    volumes:
      - meili_data:/meili_data
    ports: ["7700:7700"]
    networks: [prom-net]
    restart: unless-stopped

  minio:
    profiles: ["data"]
    image: minio/minio:RELEASE.2025-08-07T14-25-00Z
    command: ["server", "/data", "--console-address", ":9001"]
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER:-minio}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD:-minio123}
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    networks: [prom-net]
    restart: unless-stopped

  opensearch:
    profiles: ["data", "search"]
    image: opensearchproject/opensearch:2.17.0
    environment:
      - discovery.type=single-node
      - plugins.security.disabled=true
      - bootstrap.memory_lock=true
      - OPENSEARCH_JAVA_OPTS=-Xms2g -Xmx2g
    ulimits:
      memlock: { soft: -1, hard: -1 }
      nofile: { soft: 65535, hard: 65535 }
    volumes:
      - opensearch_data:/usr/share/opensearch/data
    ports: ["9200:9200", "9600:9600"]
    networks: [prom-net]
    restart: unless-stopped

  # ---------- AI / ML ----------
  ollama:
    profiles: ["ai"]
    image: ollama/ollama:0.3.14
    environment:
      - OLLAMA_KEEP_ALIVE=24h
      # enable one of: NVIDIA, ROCR, CPU, or Intel iGPU/NPU via oneAPI host libs
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: ["gpu"]
              driver: "nvidia"
    volumes:
      - /usr/share/fonts:/usr/share/fonts:ro
      - ./infra/ollama:/root/.ollama
    ports: ["11434:11434"]
    networks: [prom-net]
    restart: unless-stopped

  tei-embeddings:
    profiles: ["ai"]
    image: ghcr.io/huggingface/text-embeddings-inference:1.6
    environment:
      - MODEL_ID=${TEI_MODEL:-nomic-ai/nomic-embed-text-v1.5}
      - NUM_SHARD=1
    ports: ["8081:80"]
    networks: [prom-net]
    restart: unless-stopped

  tei-clip:
    profiles: ["ai", "vision"]
    image: ghcr.io/huggingface/text-embeddings-inference:1.6
    environment:
      - MODEL_ID=${CLIP_MODEL:-openai/clip-vit-large-patch14}
      - TASK=feature-extraction
    ports: ["8082:80"]
    networks: [prom-net]
    restart: unless-stopped

  haystack:
    profiles: ["ai", "rag"]
    image: deepset/haystack:base
    environment:
      - PIPELINE_YAML=/app/pipelines/default.yaml
    volumes:
      - ./infra/haystack:/app/pipelines
    ports: ["8000:8000"]
    networks: [prom-net]
    restart: unless-stopped
    depends_on: [opensearch, meilisearch, postgres]

  # ---------- WEB SEARCH / CRAWLING ----------
  scrapy:
    profiles: ["crawl"]
    image: ghcr.io/scrapy/scrapy:2.11
    working_dir: /workspace
    volumes:
      - ./infra/scrapy:/workspace
    networks: [prom-net]
    restart: unless-stopped

  playwright:
    profiles: ["crawl"]
    image: mcr.microsoft.com/playwright:v1.55.0-jammy
    shm_size: 1gb
    environment:
      - PLAYWRIGHT_BROWSERS_PATH=/ms-playwright
    volumes:
      - ./infra/playwright:/work
    networks: [prom-net]
    restart: unless-stopped

  selenium:
    profiles: ["crawl"]
    image: selenium/standalone-chromium:4.24.0
    shm_size: 2gb
    ports: ["4444:4444", "7900:7900"]
    networks: [prom-net]
    restart: unless-stopped

  # ---------- DEV TOOLING ----------
  sonarqube:
    profiles: ["devtools"]
    image: sonarqube:lts-community
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    volumes:
      - sonarqube_data:/opt/sonarqube/data
    ports: ["9002:9000"]
    networks: [prom-net]
    restart: unless-stopped

  gitea:
    profiles: ["devtools"]
    image: gitea/gitea:1.22.3
    environment:
      - USER_UID=1000
      - USER_GID=1000
    volumes:
      - gitea_data:/data
    ports:
      - "3001:3000"
      - "222:22"
    networks: [prom-net]
    restart: unless-stopped

  drone-server:
    profiles: ["devtools", "ci"]
    image: drone/drone:2
    environment:
      - DRONE_GITEA_SERVER=http://gitea:3000
      - DRONE_RPC_SECRET=${DRONE_RPC_SECRET:-drone-secret}
      - DRONE_SERVER_HOST=${DRONE_SERVER_HOST:-localhost:3003}
      - DRONE_SERVER_PROTO=http
    volumes:
      - drone_data:/data
    ports: ["3003:80"]
    networks: [prom-net]
    restart: unless-stopped

  code-server:
    profiles: ["devtools"]
    image: ghcr.io/coder/code-server:4.95.3
    environment:
      - PASSWORD=${CODE_SERVER_PASSWORD:-code}
    volumes:
      - code_server_data:/home/coder/project
    ports: ["8443:8443"]
    networks: [prom-net]
    restart: unless-stopped

  # ---------- SECURITY ----------
  vaultwarden:
    profiles: ["security"]
    image: vaultwarden/server:1.32.7
    environment:
      - SIGNUPS_ALLOWED=false
    volumes:
      - ./infra/vaultwarden:/data
    ports: ["8083:80"]
    networks: [prom-net]
    restart: unless-stopped

  oauth2-proxy:
    profiles: ["security"]
    image: quay.io/oauth2-proxy/oauth2-proxy:v7.6.0
    environment:
      - OAUTH2_PROXY_PROVIDER=github
      - OAUTH2_PROXY_EMAIL_DOMAINS=*
      - OAUTH2_PROXY_UPSTREAMS=http://grafana:3000
      - OAUTH2_PROXY_CLIENT_ID=${OAUTH_CLIENT_ID}
      - OAUTH2_PROXY_CLIENT_SECRET=${OAUTH_CLIENT_SECRET}
      - OAUTH2_PROXY_COOKIE_SECRET=${OAUTH_COOKIE_SECRET}
    ports: ["4180:4180"]
    networks: [prom-net]
    restart: unless-stopped

  keycloak:
    profiles: ["security"]
    image: quay.io/keycloak/keycloak:26.0
    command: start-dev
    environment:
      - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN:-admin}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD:-admin}
    ports: ["8084:8080"]
    networks: [prom-net]
    restart: unless-stopped

  crowdsec:
    profiles: ["security"]
    image: crowdsecurity/crowdsec:latest
    volumes:
      - /var/log:/var/log:ro
      - ./infra/crowdsec:/etc/crowdsec
    networks: [prom-net]
    restart: unless-stopped

  # ---------- MESSAGING ----------
  nats:
    profiles: ["messaging"]
    image: nats:2.10
    command: ["-js", "-sd", "/data"]
    volumes:
      - nats_data:/data
    ports: ["4222:4222", "8222:8222"]
    networks: [prom-net]
    restart: unless-stopped

  rabbitmq:
    profiles: ["messaging"]
    image: rabbitmq:3.13-management
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks: [prom-net]
    restart: unless-stopped

  mosquitto:
    profiles: ["messaging", "iot"]
    image: eclipse-mosquitto:2.0
    volumes:
      - ./infra/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - mosquitto_data:/mosquitto/data
    ports: ["1883:1883", "9002:9001"]
    networks: [prom-net]
    restart: unless-stopped

  # ---------- WORKFLOWS ----------
  temporal:
    profiles: ["workflows"]
    image: temporalio/auto-setup:1.25.1
    environment:
      - DB=postgresql
      - DB_PORT=5432
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PWD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_SEEDS=postgres
    depends_on: [postgres]
    ports:
      - "7233:7233"
    networks: [prom-net]
    restart: unless-stopped

  airflow:
    profiles: ["workflows"]
    image: apache/airflow:2.10.2
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://postgres:${POSTGRES_PASSWORD:-postgres}@postgres:5432/airflow
      - _AIRFLOW_WWW_USER_USERNAME=${AIRFLOW_USER:-airflow}
      - _AIRFLOW_WWW_USER_PASSWORD=${AIRFLOW_PASS:-airflow}
    user: "50000:0"
    volumes:
      - airflow_dags_data:/opt/airflow/dags
      - airflow_db_data:/opt/airflow
    depends_on: [postgres]
    ports: ["8085:8080"]
    networks: [prom-net]
    restart: unless-stopped
