// Generated by @promethean/shadow-conf
let configDotenv = () => {};

try {
  const dotenvModule = require('dotenv');

  if (typeof dotenvModule.config === 'function') {
    configDotenv = dotenvModule.config;
  }
} catch (error) {
  if (error?.code !== 'ERR_MODULE_NOT_FOUND') {
    throw error;
  }
}

configDotenv();

module.exports.apps = [];

module.exports.triggers = [];

module.exports.schedules = [];

module.exports.actions = [];
