// Generated by @promethean/shadow-conf
let configDotenv = () => {};

try {
  const dotenvModule = await import("dotenv");

  if (typeof dotenvModule.config === "function") {
    configDotenv = dotenvModule.config;
  }
} catch (error) {
  if (error?.code !== "ERR_MODULE_NOT_FOUND") {
    throw error;
  }
}

configDotenv();

export const apps = 
[];

export const triggers = 
[];

export const schedules = 
[];

export const actions = 
[];
