// Generated by @promethean/shadow-conf
import dotenv from "dotenv";

try {
  dotenv.config();
} catch (error) {
  if (error?.code !== "ERR_MODULE_NOT_FOUND") {
    throw error;
  }
}

export const apps = 
[];

export const triggers = 
[];

export const schedules = 
[];

export const actions = 
[];
