pipelines:
  - name: buildfix
    steps:
      - id: bf-errors
        shell: "pnpm --filter @promethean/buildfix bf:01-errors --tsconfig tsconfig.json --out .cache/buildfix/errors.json"
        inputs:
          - "tsconfig.json"
          - "packages/**/{src,lib}/**/*.{ts,tsx,js,jsx}"
        outputs:
          - ".cache/buildfix/errors.json"

      - id: bf-iterate
        deps: ["bf-errors"]
        shell: >
          pnpm --filter @promethean/buildfix
          bf:02-iterate
          --errors .cache/buildfix/errors.json
          --out .cache/buildfix
          --model qwen3:4b
          --max-cycles 5
        env:
          OLLAMA_URL: "${OLLAMA_URL}"
        inputs:
          - ".cache/buildfix/errors.json"
          - "tsconfig.json"
          - "packages/**/{src,lib}/**/*.{ts,tsx,js,jsx}"
        outputs:
          - ".cache/buildfix/summary.json"
          - ".cache/buildfix/history/**"
          - ".cache/buildfix/snippets/**"

      - id: bf-report
        deps: ["bf-iterate"]
        shell: "pnpm --filter @promethean/buildfix bf:03-report --summary .cache/buildfix/summary.json --history-root .cache/buildfix/history --out docs/agile/reports/buildfix"
        inputs:
          - ".cache/buildfix/summary.json"
        outputs:
          - "docs/agile/reports/buildfix/*.md"
