name: Feature request
description: Focused, practical feature proposal
title: "[feature] <summary>"
labels:
  - enhancement
  - prio:medium
  - github
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What goal or pain point does this feature address?
      placeholder: Describe the scenario, who is affected, and why it matters.
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Solution proposal
      description: Outline the approach and include a TypeScript API sketch when possible.
      placeholder: |
        interface WidgetOptions {
          readonly mode: "fast" | "safe";
        }
        export function createWidget(options: WidgetOptions): Result;
    validations:
      required: true
  - type: textarea
    id: scope
    attributes:
      label: Scope
      description: Define what is in scope and what is explicitly out of scope for this feature.
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance criteria
      description: Enumerate the success conditions for this feature.
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: TypeScript-first design (native ESM, functional style)
        - label: AVA tests cover the new behavior
        - label: Documentation updates (README/examples)
        - label: Release and rollout considerations captured
