export default {
  apps: [
    {
      name: 'frontend-chat-ui',
      script: 'shadow-cljs',
      args: 'watch chat-ui',
      cwd: '/home/err/devel/promethean/packages/frontend',
      interpreter: 'node',
      interpreter_args: '--max-old-space-size=4096',
      watch: false,
      max_memory_restart: '1G',
      env: {
        NODE_ENV: 'development',
        PORT: 8080,
      },
      env_production: {
        NODE_ENV: 'production',
        PORT: 8080,
      },
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      error_file: './logs/chat-ui-error.log',
      out_file: './logs/chat-ui-out.log',
      log_file: './logs/chat-ui-combined.log',
      time: true,
    },
    {
      name: 'frontend-docops',
      script: 'shadow-cljs',
      args: 'watch docops-frontend',
      cwd: '/home/err/devel/promethean/packages/frontend',
      interpreter: 'node',
      interpreter_args: '--max-old-space-size=4096',
      watch: false,
      max_memory_restart: '1G',
      env: {
        NODE_ENV: 'development',
        PORT: 8081,
      },
      env_production: {
        NODE_ENV: 'production',
        PORT: 8081,
      },
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      error_file: './logs/docops-error.log',
      out_file: './logs/docops-out.log',
      log_file: './logs/docops-combined.log',
      time: true,
    },
    {
      name: 'frontend-duck-web',
      script: 'shadow-cljs',
      args: 'watch duck-web-frontend',
      cwd: '/home/err/devel/promethean/packages/frontend',
      interpreter: 'node',
      interpreter_args: '--max-old-space-size=4096',
      watch: false,
      max_memory_restart: '1G',
      env: {
        NODE_ENV: 'development',
        PORT: 8082,
      },
      env_production: {
        NODE_ENV: 'production',
        PORT: 8082,
      },
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      error_file: './logs/duck-web-error.log',
      out_file: './logs/duck-web-out.log',
      log_file: './logs/duck-web-combined.log',
      time: true,
    },
    {
      name: 'frontend-kanban',
      script: 'shadow-cljs',
      args: 'watch kanban-frontend',
      cwd: '/home/err/devel/promethean/packages/frontend',
      interpreter: 'node',
      interpreter_args: '--max-old-space-size=4096',
      watch: false,
      max_memory_restart: '1G',
      env: {
        NODE_ENV: 'development',
        PORT: 8083,
      },
      env_production: {
        NODE_ENV: 'production',
        PORT: 8083,
      },
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      error_file: './logs/kanban-error.log',
      out_file: './logs/kanban-out.log',
      log_file: './logs/kanban-combined.log',
      time: true,
    },
    {
      name: 'frontend-openai-server',
      script: 'shadow-cljs',
      args: 'watch openai-server-frontend',
      cwd: '/home/err/devel/promethean/packages/frontend',
      interpreter: 'node',
      interpreter_args: '--max-old-space-size=4096',
      watch: false,
      max_memory_restart: '1G',
      env: {
        NODE_ENV: 'development',
        PORT: 8084,
      },
      env_production: {
        NODE_ENV: 'production',
        PORT: 8084,
      },
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      error_file: './logs/openai-server-error.log',
      out_file: './logs/openai-server-out.log',
      log_file: './logs/openai-server-combined.log',
      time: true,
    },
    {
      name: 'frontend-opencode-session-manager',
      script: 'shadow-cljs',
      args: 'watch opencode-session-manager-frontend',
      cwd: '/home/err/devel/promethean/packages/frontend',
      interpreter: 'node',
      interpreter_args: '--max-old-space-size=4096',
      watch: false,
      max_memory_restart: '1G',
      env: {
        NODE_ENV: 'development',
        PORT: 8085,
      },
      env_production: {
        NODE_ENV: 'production',
        PORT: 8085,
      },
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      error_file: './logs/opencode-session-manager-error.log',
      out_file: './logs/opencode-session-manager-out.log',
      log_file: './logs/opencode-session-manager-combined.log',
      time: true,
    },
    {
      name: 'frontend-piper',
      script: 'shadow-cljs',
      args: 'watch piper-frontend',
      cwd: '/home/err/devel/promethean/packages/frontend',
      interpreter: 'node',
      interpreter_args: '--max-old-space-size=4096',
      watch: false,
      max_memory_restart: '1G',
      env: {
        NODE_ENV: 'development',
        PORT: 8086,
      },
      env_production: {
        NODE_ENV: 'production',
        PORT: 8086,
      },
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      error_file: './logs/piper-error.log',
      out_file: './logs/piper-out.log',
      log_file: './logs/piper-combined.log',
      time: true,
    },
    {
      name: 'frontend-report-forge',
      script: 'shadow-cljs',
      args: 'watch report-forge-frontend',
      cwd: '/home/err/devel/promethean/packages/frontend',
      interpreter: 'node',
      interpreter_args: '--max-old-space-size=4096',
      watch: false,
      max_memory_restart: '1G',
      env: {
        NODE_ENV: 'development',
        PORT: 8087,
      },
      env_production: {
        NODE_ENV: 'production',
        PORT: 8087,
      },
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      error_file: './logs/report-forge-error.log',
      out_file: './logs/report-forge-out.log',
      log_file: './logs/report-forge-combined.log',
      time: true,
    },
    {
      name: 'frontend-smartgpt-dashboard',
      script: 'shadow-cljs',
      args: 'watch smartgpt-dashboard-frontend',
      cwd: '/home/err/devel/promethean/packages/frontend',
      interpreter: 'node',
      interpreter_args: '--max-old-space-size=4096',
      watch: false,
      max_memory_restart: '1G',
      env: {
        NODE_ENV: 'development',
        PORT: 8088,
      },
      env_production: {
        NODE_ENV: 'production',
        PORT: 8088,
      },
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      error_file: './logs/smartgpt-dashboard-error.log',
      out_file: './logs/smartgpt-dashboard-out.log',
      log_file: './logs/smartgpt-dashboard-combined.log',
      time: true,
    },
    {
      name: 'frontend-pantheon',
      script: 'vite',
      args: '--port 3000 --host 0.0.0.0',
      cwd: '/home/err/devel/promethean/packages/frontend',
      interpreter: 'node',
      interpreter_args: '--max-old-space-size=4096',
      watch: false,
      max_memory_restart: '1G',
      env: {
        NODE_ENV: 'development',
        PORT: 3000,
      },
      env_production: {
        NODE_ENV: 'production',
        PORT: 3000,
      },
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      error_file: './logs/pantheon-error.log',
      out_file: './logs/pantheon-out.log',
      log_file: './logs/pantheon-combined.log',
      time: true,
    },
  ],

  deploy: {
    production: {
      user: 'deploy',
      host: 'localhost',
      ref: 'origin/main',
      repo: 'git@github.com:promethean/frontend.git',
      path: '/var/www/promethean/frontend',
      'pre-deploy-local': '',
      'post-deploy': 'pnpm install && pnpm run build',
      'pre-setup': '',
    },
  },
};
