(ns elisp.mcp
  "Tree-sitter assisted helpers for locating and manipulating MCP blocks in Emacs Lisp files."
  (:require [clojure.string :as str]
            [elisp.read :as read])
  (:import [java.nio.charset StandardCharsets]
           [org.treesitter TSNode]))

(def ^:private generated-comment
  ";; AUTO-GENERATED by mk.mcp-cli -- edits will be overwritten.")

(def ^:private with-eval-head
  "(with-eval-after-load 'mcp")

(defn- node-text
  "Return the UTF-8 substring for `node` from `source-bytes`."
  [^TSNode node ^bytes source-bytes]
  (let [start (.getStartByte node)
        end   (.getEndByte node)
        len   (- end start)]
    (String. source-bytes start len StandardCharsets/UTF_8)))

(defn find-generated-block
  "Locate the auto-generated `(with-eval-after-load 'mcp …)` block in `source`.

  Returns a map containing:
  - `:before`: source prior to the block
  - `:after`: source after the block
  - `:block`: the block itself (comment + form)

  Returns nil when the block is absent."
  [^String source]
  (let [bytes (.getBytes source StandardCharsets/UTF_8)
        root  (read/parse-root source)
        child-count (.getNamedChildCount root)]
    (loop [idx 0]
      (if (>= idx child-count)
        nil
        (let [node (.getNamedChild root idx)
              node-type (.getType ^TSNode node)]
          (if (= "comment" node-type)
            (let [comment-text (str/trim (node-text node bytes))]
              (if (= generated-comment comment-text)
                (let [next-idx (inc idx)]
                  (when (< next-idx child-count)
                    (let [form-node (.getNamedChild root next-idx)
                          form-type (.getType ^TSNode form-node)]
                      (when (= "list" form-type)
                        (let [form-text (str/trim (node-text form-node bytes))]
                          (when (str/starts-with? form-text with-eval-head)
                            (let [start (.getStartByte node)
                                  end   (.getEndByte form-node)
                                  block (String. bytes start (- end start) StandardCharsets/UTF_8)
                                  before (String. bytes 0 start StandardCharsets/UTF_8)
                                  after  (String. bytes end (- (alength bytes) end) StandardCharsets/UTF_8)]
                              {:before before
                               :after after
                               :block block})))))))
                (recur (inc idx))))
            (recur (inc idx)))))))
