(ns elisp.mcp-test
  (:require [clojure.test :refer [deftest is testing]]
            [elisp.mcp :as sut]))

(def sample-source
  (str "(message \"before-block\")\n\n"
       ";; AUTO-GENERATED by mk.mcp-cli -- edits will be overwritten.\n"
       "(with-eval-after-load 'mcp\n"
       "  (setq mcp-hub-servers\n"
       "        '(( \"github\" .\n"
       "            (:command \"/tmp/github.sh\"))\n"
       "          )))\n\n"
       "(message \"after-block\")\n"))

(deftest find-generated-block-splits-source
  (testing "block is located with byte offsets"
    (let [{:keys [before after block block-start block-end]} (sut/find-generated-block sample-source)]
      (is (re-find #"before-block" before))
      (is (re-find #"after-block" after))
      (is (re-find #"with-eval-after-load" block))
      (is (< 0 block-start block-end))
      (is (= block (subs sample-source block-start block-end))))))

(deftest find-generated-block-missing-returns-nil
  (testing "absence of comment yields nil"
    (is (nil? (sut/find-generated-block "(message \"hello\")")))))