(ns elisp.syntax-tree-test
  (:require [clojure.string :as str]
            [clojure.test :refer [deftest is]]
            [elisp.read :as sut]))

(def sample-source
  (str ";; note: sample\n"
       ";; AUTO-GENERATED by mk.mcp-cli -- edits will be overwritten.\n"
       "(with-eval-after-load 'mcp\n"
       "  (message \"hello\"))\n"))

(defn- find-node [root pred]
  (some #(when (pred %) %)
        (tree-seq (comp seq :children) :children root)))

(deftest syntax-tree-includes-comment-and-block
  (let [{:keys [root has-errors?]} (sut/syntax-tree sample-source)
        comment-node (find-node root #(and (= "comment" (:type %))
                                           (str/starts-with? (str/trim (:text %))
                                                             ";; AUTO-GENERATED")))
        block-node (find-node root #(and (= "list" (:type %))
                                         (str/starts-with? (:text %)
                                                           "(with-eval-after-load")))]
    (is (false? has-errors?) "tree-sitter should not report syntax errors")
    (is comment-node "generated comment should be present")
    (is block-node "with-eval-after-load list should be present")
    (is (= (subs sample-source (:start-byte comment-node) (:end-byte comment-node))
           (:text comment-node)) "comment text should match source substring")
    (is (= (subs sample-source (:start-byte block-node) (:end-byte block-node))
           (:text block-node)) "block text should match source substring")
    (is (= (.indexOf sample-source ";; AUTO-GENERATED")
           (:start-byte comment-node)) "comment byte offset should align with source index")
    (is (= (.indexOf sample-source "(with-eval-after-load")
           (:start-byte block-node)) "block byte offset should align with source index")
    (is (= {:row 1 :column 0}
           (:start-point comment-node)) "generated comment should report correct line/column")
    (is (= {:row 2 :column 0}
           (:start-point block-node)) "block start point should report third line")))
