(with-eval-after-load 'gptel
  (gptel-make-ollama "Ollama"             ;Any name of your choosing
    :host "localhost:11434"               ;Where it's running
    :stream t                             ;Stream responses
    :models '(llama3.1:8b
               qwen2.5:0.5b
               nomic-embed-text:latest
               qwen2.5:7b
               gemma3:latest
               promethean-planner:latest
               qwen2.5-coder:7b
               qwen3:8b
               qwen3:4b
               gemma2:2b
               qwen2.5:3b-instruct
               llama3.2:latest))          ;List of models
  (gptel-make-openai "OpenAI Streaming"           ;Any name of your choosing
    :host "api.openai.com"         ;OpenAI's API host
    :stream t                       ;Stream responses

    :key (auth-source-pick-first-password :host "api.openai.com")
    :models '(gpt-4-turbo
               gpt-4
               gpt-3.5-turbo
               gpt-3.5-turbo-16k
               gpt-5-nano
               gpt-4.1-mini
               gpt-4.1
               gpt-4.5-preview
               gpt-5-chat-latest
               gpt-5-codex

               )
    )
  (gptel-make-openai "OpenAI Non-streaming"           ;Any name of your choosing
    :host "api.openai.com"         ;OpenAI's API host
    :stream nil                       ;Stream responses

    :key (auth-source-pick-first-password :host "api.openai.com")
    :models '(gpt-4-turbo
               gpt-4
               gpt-5
               gpt-3.5-turbo
               gpt-3.5-turbo-16k
               gpt-5-nano
               gpt-4.1-mini
               gpt-4.1
               gpt-4.5-preview
               gpt-5-chat
               gpt-5-codex))
  (gptel-make-openai "z.ai"
    :host "api.z.ai"
    :stream t
    :key (auth-source-pick-first-password :host "z.ai")
    :endpoint "/api/coding/paas/v4"
    :models `(glm-4.6 glm-4.5)))
;; AUTO-GENERATED by mk.mcp-cli -- edits will be overwritten.
(with-eval-after-load 'mcp
  (setq mcp-hub-servers
    '(("eslint" .
        (:command "npx"
          :args ("-y" "@uplinq/mcp-eslint"))
        )
       ("file-system" .
         (:command "/home/err/devel/promethean/scripts/mcp/bin/filesystem.sh"))
       ("github" .
         (:command "/home/err/devel/promethean/scripts/mcp/bin/github.sh"))
       ("github-chat" .
         (:command "/home/err/devel/promethean/scripts/mcp/bin/github_chat.sh"))
       ("http-default" .
         (:url "http://127.0.0.1:3210/mcp"))
       ("http-discord" .
         (:url "http://127.0.0.1:3210/discord"))
       ("http-exec" .
         (:url "http://127.0.0.1:3210/exec"))
       ("http-files" .
         (:url "http://127.0.0.1:3210/files"))
       ("http-github" .
         (:url "http://127.0.0.1:3210/github"))
       ("http-github-review" .
         (:url "http://127.0.0.1:3210/github/review"))
       ("http-kanban" .
         (:url "http://127.0.0.1:3210/kanban"))
       ("http-process" .
         (:url "http://127.0.0.1:3210/process"))
       ("http-workspace" .
         (:url "http://127.0.0.1:3210/workspace"))
       ("npm-helper" .
         (:command "npx"
           :args ("-y" "@pinkpixel/npm-helper-mcp"))
         )
       ("serena" .
         (:command "uvx"
           :args ("--from" "git+https://github.com/oraios/serena" "serena" "start-mcp-server"))
         )
       ("sonarqube" .
         (:command "/home/err/devel/promethean/scripts/mcp/bin/sonarqube.sh"))
       ("ts-ls-lsp" .
         (:command "npx"
           :args ("tritlo/lsp-mcp" "typescript" "/home/err/.volta/bin/typescript-language-server" "--stdio"))))))
