from __future__ import annotations

import re
from pathlib import Path

DOCS_DIR = Path('docs')
OUTPUT_FILE = DOCS_DIR / 'hashtag-index.md'

TAG_RE = re.compile(r"(?<!\w)#([A-Za-z][\w-]*)")
HEX_RE = re.compile(r"^[A-Fa-f0-9]{3}(?:[A-Fa-f0-9]{3})?$")


def collect_hashtags() -> list[str]:
    tags: set[str] = set()
    for path in DOCS_DIR.rglob('*.md'):
        if path == OUTPUT_FILE:
            continue
        text = path.read_text(encoding='utf-8')
        for tag in TAG_RE.findall(text):
            tag_lower = tag.lower()
            if HEX_RE.fullmatch(tag_lower):
                continue
            tags.add(tag_lower)
    return sorted(tags)


def build_document(tags: list[str]) -> str:
    lines = [
        '# Hashtag Index',
        '',
        'This file is auto-generated by `scripts/generate_hashtags_doc.py`.',
        '',
        '## Tags',
    ]
    for tag in tags:
        lines.append(f'- #{tag}')
    lines.append('')
    lines.append('#docs #hashtags')
    lines.append('')
    return '\n'.join(lines)


def main() -> None:
    tags = collect_hashtags()
    content = build_document(tags)
    OUTPUT_FILE.write_text(content + '\n', encoding='utf-8')


if __name__ == '__main__':
    main()
