import { describe, it, expect } from "vitest";
import { start } from "../src/agent.js";
import { makeMockRuntime } from "./mockRuntime.js";
import inFixture from "./golden/v1/in/example.json";
import outFixture from "./golden/v1/out/example.json";

describe("stateless agent template", () => {
  it("produces deterministic output for same input", async () => {
    const rt = makeMockRuntime();
    await start(rt as any);

    await rt.emit(
      "promethean.p.discord.t.duck.voice.audio.segment",
      inFixture as any,
    );
    const outs = rt.getPublished();
    expect(outs.length).toBe(1);

    // wipe autogenerated ids/timestamps before compare
    const norm = { ...outs[0], id: undefined, ts: undefined };
    const expected = { ...(outFixture as any), id: undefined, ts: undefined };
    expect(norm).toEqual(expected);
  });
});
