/**
 * Agent Coordination System Types
 *
 * Unified type system for agent instance management, task assignment,
 * and real-time coordination in Promethean Agent OS.
 */

// Agent instance management types
export * from './agent-instance.js';

// Coordination types - select exports to avoid conflicts
export type {
  AgentCoordinator,
  Team,
  TeamConfig,
  AgentMessage,
  BroadcastMessage,
  ChannelConfig,
  CoordinationStatus,
  AgentMetrics,
  TeamMetrics,
  TaskRequirements,
  TaskAssignment,
  OptimizationGoal,
  AssignmentStrategy,
  AssignmentWeights,
  AssignmentReasoning,
  AlternativeAssignment,
  IssueSeverity,
  IssueType,
  CollaborationNeed,
  CapabilityRequirement,
  ResourceRequirement,
  TaskType,
  DeliveryReceipt,
  MessageAttachment,
  MessagePriority,
  MessageStatus,
  MessageType,
} from './coordination.js';

// Task assignment types - select exports to avoid conflicts
export type {
  TaskAnalysis,
  AssignmentDecision,
  DependencyType,
  ResourceConstraint,
  ResourceType,
  TaskDependency,
  ToolAccessLevel,
  ToolRequirement,
  RecommendationType,
  ComplexityAssessment,
  ComplexityFactor,
  SkillRequirement,
  CapabilityRequirement as TaskCapabilityRequirement,
  ResourceRequirement as TaskResourceRequirement,
  ToolRequirement as TaskToolRequirement,
  EnvironmentConstraint,
  LearningOpportunity,
  KnowledgeTransfer,
  CollaborationNeed as TaskCollaborationNeed,
  TaskType as TaskAssignmentType,
  SecurityLevel as TaskSecurityLevel,
  TaskPriority as TaskAssignmentPriority,
} from './task-assignment.js';

// Integration types - select exports to avoid conflicts
export type {
  EnsoIntegrationManager,
  EnsoRoom,
  AgentRoomConfig,
  RoomType,
  RoomPurpose,
  RoomSettings,
  RoomPermissions,
  RoomParticipant,
  ParticipantRole,
  ParticipantStatus,
  RoomStatus,
  TaskContext,
  TaskMilestone,
  TaskResource,
  ResourceStatus,
  SharedResource,
  AccessLevel,
  ResourceUsage,
  ResourceConstraint as EnsoResourceConstraint,
  TaskBlocker as EnsoTaskBlocker,
  BlockerType,
  BlockerSeverity,
  CommunicationEntry,
  CommunicationType,
  CommunicationAttachment,
  TaskDecision,
  DecisionOption,
  TaskLesson,
  LessonCategory,
  LessonSeverity,
  TaskArtifact,
  ArtifactType,
  SharedContext,
  ContextType,
  ContextPermissions,
  AgentCapability as EnsoAgentCapability,
  CapabilityEndorsement,
  CapabilityCertification,
  CapabilityMetadata,
  LearningResource,
  AssessmentCriteria,
  SharedCapability,
  SharingLevel,
  AccessCondition,
  ConditionType,
  CapabilityUsage,
  CapabilityFeedback,
  CapabilityRequest,
  RequestUrgency,
  CapabilityResponse,
  ResponseType,
  AgentTool,
  ToolType,
  ToolAccessLevel as EnsoToolAccessLevel,
  ToolPermission,
  ToolConfiguration,
  ToolRequirement as EnsoToolRequirement,
  ToolParameter,
  ParameterType,
  ValidationRule,
  ValidationType,
  ToolSetting,
  ToolUsage,
  ToolDocumentation,
  ToolExample,
  ToolAPI,
  APIEndpoint,
  HTTPMethod,
  APIParameter,
  APIResponse,
  AuthenticationMethod,
  RateLimit,
  TroubleshootingEntry,
  ToolEndpoint,
  EndpointType,
  ToolEvent,
  EventPayload,
  EventTrigger,
  ToolMetadata,
  CompatibilityInfo,
  SecurityInfo,
  SecurityVulnerability,
  DataHandlingPolicy,
  SharedTool,
  ToolFeedback,
  ToolAvailability,
  AvailabilityIssue,
  ToolAccessRequest,
  ToolAccessResponse,
  CoordinationMessage,
  MessageType as EnsoMessageType,
  MessagePriority as EnsoMessagePriority,
  MessageStatus as EnsoMessageStatus,
  DeliveryReceipt as EnsoDeliveryReceipt,
  MessageAttachment as EnsoMessageAttachment,
  AgentBroadcast,
  BroadcastType,
  BroadcastAudience,
  BroadcastFilter,
  BroadcastStatus,
  DeliveryStats,
  TaskStatus as EnsoTaskStatus,
  ResourceType as EnsoResourceType,
  TaskDependency as EnsoTaskDependency,
  DependencyType as EnsoDependencyType,
} from './enso-integration.js';

export type {
  KanbanIntegrationManager,
  AgentKanbanStatus,
  AgentTask,
  AgentWorkload,
  WIPStatus,
  WIPStatusType,
  AgentAvailability,
  AgentBoard,
  BoardColumn,
  ColumnType,
  ColumnWIPLimit,
  BoardTask,
  BacklogTask,
  BoardSettings,
  TaskFilter,
  FilterOperator,
  BoardStatus,
  BoardMetrics,
  AgentBoardConfig,
  BoardColumnConfig,
  ColumnWIPLimitConfig,
  TaskAutomation,
  AutomationTrigger,
  TriggerType,
  AutomationCondition,
  ConditionType as KanbanConditionType,
  ConditionOperator,
  AutomationAction,
  ActionType,
  AutomationStatus,
  AutomationExecution,
  ConditionEvaluation,
  ActionResult,
  ActionStatus,
  ExecutionStatus,
  TaskAutomationConfig,
  TaskProgress,
  TaskPhase,
  PhaseStatus,
  PhaseProgress,
  WorkItem,
  WorkItemType,
  WorkItemStatus,
  QualityCheck,
  QualityCheckType,
  QualityCheckStatus,
  QualityCheckResult,
  QualityIssue,
  QualityIssueType,
  QualityIssueSeverity,
  QualityMetric,
  TaskIssue,
  TaskIssueType,
  TaskIssueSeverity,
  ProgressUpdate,
  UpdateType,
  WIPLimit,
  WIPAdjustmentCriteria,
  WIPAdjustmentFactor,
  AnalyticsPeriod,
  PeriodType,
  AgentAnalytics,
  TeamAnalytics,
  SystemAnalytics,
  AnalyticsTrend,
  AnalyticsInsight,
  InsightType,
  InsightImpact,
  AnalyticsRecommendation,
  RecommendationType as KanbanRecommendationType,
  RecommendationPriority,
  RecommendationEffort,
  TeamBottleneck,
  BottleneckType,
  AgentTypeDistribution,
  TaskTypeDistribution,
  StatusDistribution,
  TaskBlocker as KanbanTaskBlocker,
  BlockerType as KanbanBlockerType,
  BlockerSeverity as KanbanBlockerSeverity,
  TaskDependency as KanbanTaskDependency,
  DependencyType as KanbanDependencyType,
} from './kanban-integration.js';
